# Generated by Django 6.0.1 on 2026-01-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé'), ('critical', 'Critique')], max_length=10, verbose_name='Sévérité')),
                ('message', models.TextField(verbose_name='Message')),
                ('value', models.FloatField(blank=True, null=True, verbose_name='Valeur mesurée')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('timestamp', models.DateTimeField(verbose_name='Date/Heure')),
                ('is_acknowledged', models.BooleanField(default=False, verbose_name='Acquittée')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='Acquittée le')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
                'db_table': 'alerts',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la règle')),
                ('alert_type', models.CharField(choices=[('speed', 'Excès de vitesse'), ('idle', 'Arrêt prolongé'), ('geofence_exit', 'Sortie de zone'), ('geofence_entry', 'Entrée dans zone'), ('device_offline', 'Coupure boîtier'), ('fuel_theft', 'Vol de carburant'), ('fuel_leak', 'Fuite de carburant'), ('harsh_braking', 'Freinage brusque'), ('harsh_acceleration', 'Accélération brusque')], max_length=30, verbose_name="Type d'alerte")),
                ('threshold_value', models.FloatField(verbose_name='Valeur seuil')),
                ('threshold_unit', models.CharField(blank=True, max_length=20, verbose_name='Unité')),
                ('email_notifications', models.BooleanField(default=False, verbose_name='Notifications email')),
                ('email_recipients', models.TextField(blank=True, verbose_name='Destinataires email (séparés par ;)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Règle d'alerte",
                'verbose_name_plural': "Règles d'alerte",
                'db_table': 'alert_rules',
            },
        ),
        migrations.CreateModel(
            name='Geofence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la zone')),
                ('shape_type', models.CharField(choices=[('circle', 'Cercle'), ('polygon', 'Polygone')], max_length=20, verbose_name='Type de forme')),
                ('center_latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('center_longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('radius', models.FloatField(blank=True, null=True, verbose_name='Rayon (m)')),
                ('coordinates', models.JSONField(blank=True, null=True, verbose_name='Coordonnées polygone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Zone géographique',
                'verbose_name_plural': 'Zones géographiques',
                'db_table': 'geofences',
            },
        ),
    ]
