# Generated by Django 6.0.1 on 2026-01-26 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Date début')),
                ('end_date', models.DateField(verbose_name='Date fin')),
                ('distance', models.FloatField(verbose_name='Distance (km)')),
                ('fuel_consumed', models.FloatField(verbose_name='Carburant consommé (L)')),
                ('avg_consumption', models.FloatField(verbose_name='Consommation moyenne (L/100km)')),
                ('fuel_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Coût carburant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_consumptions', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Consommation carburant',
                'verbose_name_plural': 'Consommations carburant',
                'db_table': 'fuel_consumptions',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='FuelEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('refuel', 'Plein'), ('theft', 'Vol suspect'), ('leak', 'Fuite'), ('consumption_anomaly', 'Consommation anormale')], max_length=30, verbose_name="Type d'événement")),
                ('fuel_before', models.FloatField(verbose_name='Niveau avant (L)')),
                ('fuel_after', models.FloatField(verbose_name='Niveau après (L)')),
                ('fuel_difference', models.FloatField(verbose_name='Différence (L)')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('timestamp', models.DateTimeField(verbose_name='Date/Heure')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Confirmé')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_events', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Événement carburant',
                'verbose_name_plural': 'Événements carburant',
                'db_table': 'fuel_events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FuelReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_level', models.FloatField(verbose_name='Niveau (litres)')),
                ('fuel_percentage', models.FloatField(verbose_name='Pourcentage (%)')),
                ('timestamp', models.DateTimeField(verbose_name='Date/Heure')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_readings', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Lecture carburant',
                'verbose_name_plural': 'Lectures carburant',
                'db_table': 'fuel_readings',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['vehicle', '-timestamp'], name='fuel_readin_vehicle_e9a72e_idx')],
            },
        ),
    ]
