# Generated by Django 6.0.1 on 2026-01-26 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('start_longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('end_latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('end_longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('distance', models.FloatField(default=0, verbose_name='Distance (km)')),
                ('max_speed', models.FloatField(default=0, verbose_name='Vitesse max (km/h)')),
                ('avg_speed', models.FloatField(default=0, verbose_name='Vitesse moyenne (km/h)')),
                ('start_time', models.DateTimeField(verbose_name='Heure de départ')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name="Heure d'arrivée")),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Durée')),
                ('idle_time', models.DurationField(blank=True, null=True, verbose_name="Temps d'arrêt")),
                ('is_completed', models.BooleanField(default=False, verbose_name='Trajet terminé')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Trajet',
                'verbose_name_plural': 'Trajets',
                'db_table': 'trips',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='StopPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('start_time', models.DateTimeField(verbose_name='Début arrêt')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Fin arrêt')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Durée arrêt')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_points', to='tracking.trip')),
            ],
            options={
                'verbose_name': "Point d'arrêt",
                'verbose_name_plural': "Points d'arrêt",
                'db_table': 'stop_points',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='Longitude')),
                ('altitude', models.FloatField(blank=True, null=True, verbose_name='Altitude (m)')),
                ('speed', models.FloatField(default=0, verbose_name='Vitesse (km/h)')),
                ('heading', models.IntegerField(default=0, verbose_name='Direction (degrés)')),
                ('engine_on', models.BooleanField(default=False, verbose_name='Moteur allumé')),
                ('ignition', models.BooleanField(default=False, verbose_name='Contact')),
                ('timestamp', models.DateTimeField(verbose_name='Date/Heure GPS')),
                ('server_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date/Heure serveur')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Position GPS',
                'verbose_name_plural': 'Positions GPS',
                'db_table': 'positions',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['vehicle', '-timestamp'], name='positions_vehicle_2cc501_idx'), models.Index(fields=['timestamp'], name='positions_timesta_efe75d_idx')],
            },
        ),
    ]
