# Generated by Django 6.0.1 on 2026-01-26 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nom')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('license_number', models.CharField(max_length=20, unique=True, verbose_name='Numéro de permis')),
                ('license_expiry', models.DateField(blank=True, null=True, verbose_name='Expiration permis')),
                ('rfid_tag', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Badge RFID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name="Date d'embauche")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authorized_vehicles', models.ManyToManyField(blank=True, related_name='authorized_drivers', to='vehicles.vehicle', verbose_name='Véhicules autorisés')),
            ],
            options={
                'verbose_name': 'Conducteur',
                'verbose_name_plural': 'Conducteurs',
                'db_table': 'drivers',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='DriverSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Début session')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Fin session')),
                ('distance', models.FloatField(default=0, verbose_name='Distance parcourue (km)')),
                ('max_speed', models.FloatField(default=0, verbose_name='Vitesse max (km/h)')),
                ('avg_speed', models.FloatField(default=0, verbose_name='Vitesse moyenne (km/h)')),
                ('harsh_braking_count', models.IntegerField(default=0, verbose_name='Freinages brusques')),
                ('harsh_acceleration_count', models.IntegerField(default=0, verbose_name='Accélérations brusques')),
                ('is_active', models.BooleanField(default=True, verbose_name='Session active')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='drivers.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_sessions', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Session de conduite',
                'verbose_name_plural': 'Sessions de conduite',
                'db_table': 'driver_sessions',
                'ordering': ['-start_time'],
            },
        ),
    ]
