# Generated by Django 6.0.1 on 2026-01-26 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=20, unique=True, verbose_name='IMEI')),
                ('device_type', models.CharField(choices=[('gps', 'Boîtier GPS'), ('fuel_sensor', 'Capteur carburant'), ('rfid', 'Lecteur RFID'), ('canbus', 'CAN Bus')], max_length=20, verbose_name='Type')),
                ('brand', models.CharField(choices=[('teltonika', 'Teltonika'), ('coban', 'Coban'), ('sinotrack', 'Sinotrack'), ('other', 'Autre')], max_length=20, verbose_name='Marque')),
                ('model', models.CharField(blank=True, max_length=50, verbose_name='Modèle')),
                ('sim_number', models.CharField(blank=True, max_length=20, verbose_name='Numéro SIM')),
                ('apn', models.CharField(blank=True, max_length=50, verbose_name='APN')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('last_communication', models.DateTimeField(blank=True, null=True, verbose_name='Dernière communication')),
                ('installation_date', models.DateField(blank=True, null=True, verbose_name="Date d'installation")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='vehicles.vehicle', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Boîtier/Capteur',
                'verbose_name_plural': 'Boîtiers/Capteurs',
                'db_table': 'devices',
            },
        ),
    ]
