# Generated by Django 6.0.1 on 2026-01-30 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='core.company'),
        ),
        migrations.AddField(
            model_name='device',
            name='protocol',
            field=models.CharField(choices=[('teltonika', 'Teltonika Binary'), ('coban', 'Coban ASCII'), ('sinotrack', 'Sinotrack Binary')], default='teltonika', max_length=20, verbose_name='Protocole'),
        ),
        migrations.AlterField(
            model_name='device',
            name='imei',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='IMEI'),
        ),
    ]
