# Generated by Django 6.0.1 on 2026-01-30 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Null uniquement pour SUPER_ADMIN', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Administrateur'), ('admin', 'Administrateur'), ('supervisor', 'Superviseur'), ('user', 'Utilisateur simple')], default='user', max_length=20),
        ),
    ]
