# Generated by Django 6.0.1 on 2026-01-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, unique=True, verbose_name='Immatriculation')),
                ('vehicle_type', models.CharField(choices=[('car', 'Véhicule'), ('motorcycle', 'Moto'), ('truck', 'Camion'), ('equipment', 'Engin'), ('other', 'Autre')], max_length=20, verbose_name='Type')),
                ('brand', models.CharField(blank=True, max_length=50, verbose_name='Marque')),
                ('model', models.CharField(blank=True, max_length=50, verbose_name='Modèle')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Année')),
                ('color', models.CharField(blank=True, max_length=30, verbose_name='Couleur')),
                ('fuel_capacity', models.FloatField(blank=True, null=True, verbose_name='Capacité carburant (L)')),
                ('fuel_type', models.CharField(blank=True, max_length=20, verbose_name='Type de carburant')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
                'db_table': 'vehicles',
                'ordering': ['license_plate'],
            },
        ),
    ]
