# Generated by Django 6.0.1 on 2026-01-26 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('report_type', models.CharField(choices=[('vehicle', 'Rapport véhicule'), ('driver', 'Rapport conducteur'), ('fleet', 'Rapport flotte'), ('fuel', 'Rapport carburant'), ('alerts', 'Rapport alertes'), ('trips', 'Rapport trajets'), ('consumption', 'Rapport consommation')], max_length=20, verbose_name='Type')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='pdf', max_length=10)),
                ('frequency', models.CharField(choices=[('daily', 'Quotidien'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel')], max_length=20, verbose_name='Fréquence')),
                ('day_of_week', models.IntegerField(blank=True, null=True, verbose_name='Jour de la semaine (0-6)')),
                ('day_of_month', models.IntegerField(blank=True, null=True, verbose_name='Jour du mois (1-31)')),
                ('time', models.TimeField(verbose_name="Heure d'envoi")),
                ('email_recipients', models.TextField(verbose_name='Destinataires email (séparés par ;)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='Dernière exécution')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Planification rapport',
                'verbose_name_plural': 'Planifications rapports',
                'db_table': 'report_schedules',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du rapport')),
                ('report_type', models.CharField(choices=[('vehicle', 'Rapport véhicule'), ('driver', 'Rapport conducteur'), ('fleet', 'Rapport flotte'), ('fuel', 'Rapport carburant'), ('alerts', 'Rapport alertes'), ('trips', 'Rapport trajets'), ('consumption', 'Rapport consommation')], max_length=20, verbose_name='Type')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='pdf', max_length=10, verbose_name='Format')),
                ('start_date', models.DateField(verbose_name='Date début')),
                ('end_date', models.DateField(verbose_name='Date fin')),
                ('file_path', models.CharField(blank=True, max_length=255, verbose_name='Chemin fichier')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='Taille (octets)')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Généré le')),
                ('statistics', models.JSONField(blank=True, null=True, verbose_name='Statistiques')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drivers.driver', verbose_name='Conducteur')),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
                'db_table': 'reports',
                'ordering': ['-generated_at'],
            },
        ),
    ]
